artifacts_root: artifacts


data_ingestion :
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Fezzaioussama/Custom-dataloder/raw/main/Dataset_housing_price.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
